import { Head } from "@absolutejs/absolute/react/components";
import { useMemo, useState } from "react";
import { CARD_VARIANTS, generate, type CardVariant } from "../../../shared/procgen.ts";
import { spriteToSvg } from "../../../shared/petSvg.ts";
import { SiteHeader } from "../components/SiteHeader";

type Copy = { seed: string; printingId: string | null; owner: string | null; ownerHandle: string; ownerIsAi: boolean; name: string; tier: string; finish: string | null; mutation: string | null; material: string | null; colorway: string | null; pattern: string | null; serialNumber: number | null; supply: number | null; rarityScore: number; size: number; earnedAt: string };
type Population = { id: string; variant: string; finish: string; supply: number; issued: number; remaining: number; discovered: number; listed: number; issuedPercent: number };
type Listing = { id: string; petSeed: string; priceCents: number; seller: string | null; sellerHandle: string; finish: string | null; material: string | null; colorway: string | null; pattern: string | null; serialNumber: number | null; supply: number | null; rarityScore: number; size: number };
type BuyOrder = { id: string; buyer: string | null; buyerHandle: string; criteria: { finish?: string; material?: string; colorway?: string; pattern?: string; maxSerial?: number }; priceCents: number; expiresAt: string | null };
type Auction = { id: string; petSeed: string; seller: string | null; sellerHandle: string; startCents: number; reserveCents: number | null; endsAt: string; finish: string | null; serialNumber: number | null; supply: number | null };
type Sale = { petSeed: string; amountCents: number | null; reason: string; occurredAt: string; finish: string | null; material: string | null; colorway: string | null; pattern: string | null; serialNumber: number | null; supply: number | null };
type Exchange = {
  subject: { id: string; setId: string; slotNumber: number; name: string; subjectSeed: string };
  population: Population[]; copies: Copy[]; listings: Listing[]; buyOrders: BuyOrder[]; auctions: Auction[]; sales: Sale[];
  saleGroups: { finish: string; count: number; averageCents: number; lowCents: number; highCents: number }[];
  census: Record<"finishes" | "materials" | "colorways" | "patterns" | "mutations", { value: string; count: number }[]>;
  records: { lowestSerial: Copy | null; largest: Copy | null; rarest: Copy | null };
  watchCount: number; summary: { discovered: number; listed: number; floorCents: number | null; highestBuyOrderCents: number | null; sales: number };
};
type Watch = { finish: string | null; maximumPriceCents: number | null };

const money = (cents: number | null) => cents == null ? "—" : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(cents / 100);
const petSvg = (seed: string, box = 104) => { const rendered = spriteToSvg(generate(seed), { box }); return `<svg viewBox="0 0 ${rendered.width} ${rendered.height}" aria-hidden="true"><g>${rendered.svg}</g></svg>`; };
const odds = (variant: string) => { const cfg = CARD_VARIANTS[variant as CardVariant]; return cfg ? `1 in ${cfg.pullOdds.toLocaleString(undefined, { maximumFractionDigits: 0 })}` : "Edition odds unavailable"; };

const CopyCard = ({ copy, selected, toggle }: { copy: Copy; selected: boolean; toggle: () => void }) => <article className={`exchangeCopy${selected ? " selected" : ""}`}>
  <a href={`/pet/${encodeURIComponent(copy.seed)}`} className="exchangeArt" dangerouslySetInnerHTML={{ __html: petSvg(copy.seed) }} />
  <div><strong>{copy.finish} #{copy.serialNumber?.toLocaleString()}</strong><span>{copy.material} · {copy.colorway}</span><span>{copy.pattern} · size {copy.size}</span><a href={copy.owner ? `/profile/${encodeURIComponent(copy.owner)}` : "#"}>{copy.owner ? `@${copy.owner}${copy.ownerIsAi ? " 🤖" : ""}` : copy.ownerHandle}</a></div>
  <button onClick={toggle}>{selected ? "Remove comparison" : "Compare"}</button>
</article>;

export const RenownPetExchange = ({ cssPath, exchange, origin = "" }: { cssPath?: string; exchange: Exchange | null; origin?: string }) => {
  const [selected, setSelected] = useState<string[]>([]); const [watch, setWatch] = useState<Watch | null>(null); const [signedIn, setSignedIn] = useState<boolean | null>(null);
  const [watchFinish, setWatchFinish] = useState(""); const [watchPrice, setWatchPrice] = useState(""); const [notice, setNotice] = useState(""); const [watchPanel, setWatchPanel] = useState(false);
  const compared = useMemo(() => exchange?.copies.filter((copy) => selected.includes(copy.seed)) ?? [], [exchange, selected]);
  if (!exchange) return <html lang="en"><Head cssPath={cssPath} title="Pet exchange — Renown" description="This pet subject has not been discovered." /><body><main className="wrap exchangePage"><SiteHeader back={{ href: "/pets?view=books", label: "Back to collector books" }} /><section className="collectionEmpty"><h1>Subject not discovered</h1><p>This Genesis slot remains hidden until its first public copy is earned.</p></section></main></body></html>;
  const toggle = (seed: string) => setSelected((current) => current.includes(seed) ? current.filter((item) => item !== seed) : current.length < 3 ? [...current, seed] : [...current.slice(1), seed]);
  const openWatch = async () => { setWatchPanel(true); const response = await fetch(`/api/account/marketplace/subjects/${encodeURIComponent(exchange.subject.id)}/watch`); setSignedIn(response.ok); if (response.ok) { const body = await response.json() as { watch: Watch | null }; setWatch(body.watch); setWatchFinish(body.watch?.finish ?? ""); setWatchPrice(body.watch?.maximumPriceCents ? String(body.watch.maximumPriceCents / 100) : ""); } };
  const saveWatch = async () => { const response = await fetch(`/api/account/marketplace/subjects/${encodeURIComponent(exchange.subject.id)}/watch`, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ finish: watchFinish || undefined, maximumPriceCents: watchPrice ? Math.round(Number(watchPrice) * 100) : undefined }) }); if (response.ok) { const body = await response.json() as { watch: Watch }; setWatch(body.watch); setNotice("Watch saved. We’ll notify you when a matching copy reaches the market."); } else setNotice(await response.text()); };
  const removeWatch = async () => { await fetch(`/api/account/marketplace/subjects/${encodeURIComponent(exchange.subject.id)}/watch`, { method: "DELETE" }); setWatch(null); setWatchFinish(""); setWatchPrice(""); setNotice("Watch removed."); };
  const description = `${exchange.subject.name} population, individual copies, listings, buy orders, auctions, and public sale history.`;
  return <html lang="en"><Head cssPath={cssPath} title={`${exchange.subject.name} exchange — Renown`} description={description} canonical={`${origin}/marketplace/subjects/${encodeURIComponent(exchange.subject.id)}`} /><body><main className="wrap exchangePage">
    <SiteHeader back={{ href: "/marketplace", label: "Back to marketplace" }} />
    <section className="exchangeHero"><div><span className="collectionEyebrow">{exchange.subject.setId.toUpperCase()} · SUBJECT #{String(exchange.subject.slotNumber).padStart(3, "0")}</span><h1>{exchange.subject.name}</h1><p>Every known parallel and physical copy, with live demand, population, records, and public comparable sales.</p></div><div className="exchangeHeroStats"><div><strong>{exchange.summary.discovered}</strong><span>copies discovered</span></div><div><strong>{money(exchange.summary.floorCents)}</strong><span>current floor</span></div><div><strong>{money(exchange.summary.highestBuyOrderCents)}</strong><span>best instant offer</span></div></div></section>

    <section className="exchangeWatch"><div><span>CHASE ALERT · {exchange.watchCount} WATCHING</span><h2>{watch ? "You’re watching this subject" : "Know when the right copy appears"}</h2><p>Choose any finish or narrow the alert to a maximum listing price.</p></div>{!watchPanel ? <button onClick={() => void openWatch()}>Set chase alert</button> : signedIn ? <div><select value={watchFinish} onChange={(event) => setWatchFinish(event.target.value)}><option value="">Any finish</option>{exchange.population.map((row) => <option key={row.id} value={row.finish}>{row.finish}</option>)}</select><label><span>$</span><input inputMode="decimal" value={watchPrice} onChange={(event) => setWatchPrice(event.target.value)} placeholder="Any price" /></label><button onClick={() => void saveWatch()}>{watch ? "Update watch" : "Watch subject"}</button>{watch && <button className="tradeSecondary" onClick={() => void removeWatch()}>Remove</button>}</div> : <a className="btn solid" href="/">Sign in to watch</a>}</section>{notice && <p className="exchangeNotice">{notice}</p>}

    <section className="exchangeSection"><header><div><span>KNOWN LIMITS</span><h2>Parallel population</h2></div><p>Supply never changes. Serials are shuffled; issued shows how many physical copies currently exist.</p></header><div className="exchangePopulation">{exchange.population.map((row) => <article key={row.id}><div><span>{row.finish}</span><strong>{row.variant.replaceAll("-", " ")}</strong></div><dl><div><dt>Supply</dt><dd>/{row.supply.toLocaleString()}</dd></div><div><dt>Issued</dt><dd>{row.issued.toLocaleString()}</dd></div><div><dt>Remaining</dt><dd>{row.remaining.toLocaleString()}</dd></div><div><dt>Market</dt><dd>{row.listed}</dd></div></dl><small>{odds(row.variant)} per earned pull</small><i><b style={{ width: `${Math.max(row.issuedPercent, row.issued ? .5 : 0)}%` }} /></i></article>)}</div></section>

    <section className="exchangeSection"><header><div><span>LIVE MARKET</span><h2>Supply meets demand</h2></div><a href={`/marketplace?buyOrder=${encodeURIComponent(exchange.copies[0]?.seed ?? "")}`}>Post a buy order</a></header><div className="exchangeMarketColumns"><div><h3>Listings</h3>{exchange.listings.length ? exchange.listings.map((row) => <a className="exchangeMarketRow" href={`/marketplace?buy=${encodeURIComponent(row.id)}`} key={row.id}><span dangerouslySetInnerHTML={{ __html: petSvg(row.petSeed, 54) }} /><div><strong>{row.finish} #{row.serialNumber}</strong><small>{row.material} · {row.colorway}</small></div><b>{money(row.priceCents)}</b></a>) : <p>No copies listed.</p>}</div><div><h3>Buy orders</h3>{exchange.buyOrders.length ? exchange.buyOrders.map((row) => <article className="exchangeMarketRow" key={row.id}><div><strong>{row.criteria.finish ?? "Any parallel"}</strong><small>{[row.criteria.material, row.criteria.colorway, row.criteria.pattern, row.criteria.maxSerial ? `serial ≤ ${row.criteria.maxSerial}` : null].filter(Boolean).join(" · ") || "Any matching copy"}</small></div><b>{money(row.priceCents)}</b></article>) : <p>No open buy orders.</p>}</div><div><h3>Auctions</h3>{exchange.auctions.length ? exchange.auctions.map((row) => <a className="exchangeMarketRow" href="/marketplace" key={row.id}><span dangerouslySetInnerHTML={{ __html: petSvg(row.petSeed, 54) }} /><div><strong>{row.finish} #{row.serialNumber}</strong><small>Ends {new Date(row.endsAt).toLocaleString()}</small></div><b>{money(row.startCents)}</b></a>) : <p>No live auctions.</p>}</div></div></section>

    <section className="exchangeSection"><header><div><span>PHYSICAL COPIES</span><h2>Compare discovered copies</h2></div><p>Select up to three. A low serial can be desirable, but it does not change the published pull odds.</p></header>{compared.length > 0 && <div className="exchangeCompare"><table><thead><tr><th>Copy</th>{compared.map((copy) => <th key={copy.seed}>{copy.finish} #{copy.serialNumber}</th>)}</tr></thead><tbody>{(["material", "colorway", "pattern", "mutation", "size", "rarityScore"] as const).map((key) => <tr key={key}><th>{key === "rarityScore" ? "Rarity score" : key}</th>{compared.map((copy) => <td key={copy.seed}>{copy[key]}</td>)}</tr>)}</tbody></table></div>}<div className="exchangeCopies">{exchange.copies.map((copy) => <CopyCard key={copy.seed} copy={copy} selected={selected.includes(copy.seed)} toggle={() => toggle(copy.seed)} />)}</div></section>

    <section className="exchangeSection exchangeRecords"><header><div><span>KNOWN RECORDS</span><h2>What makes this subject collectible</h2></div></header><div>{[["Lowest discovered serial", exchange.records.lowestSerial, exchange.records.lowestSerial ? `#${exchange.records.lowestSerial.serialNumber}/${exchange.records.lowestSerial.supply}` : "—"], ["Largest known copy", exchange.records.largest, exchange.records.largest ? `Size ${exchange.records.largest.size}` : "—"], ["Highest rarity score", exchange.records.rarest, exchange.records.rarest ? exchange.records.rarest.rarityScore.toFixed(2) : "—"]].map(([label, copy, value]) => <article key={String(label)}>{copy && typeof copy === "object" && "seed" in copy ? <a href={`/pet/${encodeURIComponent(copy.seed)}`} dangerouslySetInnerHTML={{ __html: petSvg(copy.seed, 80) }} /> : null}<span>{String(label)}</span><strong>{String(value)}</strong></article>)}</div></section>

    <section className="exchangeSection"><header><div><span>TRAIT CENSUS</span><h2>Known combinations</h2></div><p>Counts describe discovered copies, not future guarantees.</p></header><div className="exchangeCensus">{Object.entries(exchange.census).map(([group, rows]) => <article key={group}><h3>{group}</h3>{rows.slice(0, 10).map((row) => <div key={row.value}><span>{row.value}</span><strong>{row.count}</strong></div>)}</article>)}</div></section>

    <section className="exchangeSection"><header><div><span>PUBLIC COMPARABLES</span><h2>Sale history</h2></div><p>Historical trades are references, never appraisals or promises of future value.</p></header>{exchange.saleGroups.length > 0 && <div className="exchangeSaleStats">{exchange.saleGroups.map((group) => <article key={group.finish}><span>{group.finish}</span><strong>{money(group.averageCents)} average</strong><small>{group.count} sale{group.count === 1 ? "" : "s"} · {money(group.lowCents)}–{money(group.highCents)}</small></article>)}</div>}{exchange.sales.length ? <div className="exchangeSales">{exchange.sales.map((sale) => <a href={`/pet/${encodeURIComponent(sale.petSeed)}`} key={`${sale.petSeed}:${sale.occurredAt}`}><div><strong>{sale.finish} #{sale.serialNumber}</strong><span>{sale.material} · {sale.colorway} · {sale.pattern}</span></div><b>{money(sale.amountCents)}</b><time>{new Date(sale.occurredAt).toLocaleDateString()}</time></a>)}</div> : <div className="collectionEmpty"><h3>No public sale yet</h3><p>The first atomic sale will establish the first comparable for this subject.</p></div>}</section>
  </main></body></html>;
};
